services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=${SPRING_DATASOURCE_DB}'
      - 'POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}'
      - 'POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: